obstacle_range: 2.0
raytrace_range: 5.0
robot_radius: 0.14
inflation_radius: 0.13
max_obstacle_height: 0.6
min_obstacle_height: 0.0
observation_sources: scan
scan: {sensor_frame: camera_depth_optical_frame, data_type: PointCloud2, topic: /camera/depth/points, marking: true, clearing: false, observation_persistence: 0.0, expected_update_rate: 0.2}
